name: Go

env:
  GIN_MODE: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
        cache: true

    - name: Revive Action
      uses: morphy2k/revive-action@v2.4.1

    - name: Install Staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@v0.6.1
        echo "${HOME}/go/bin" >> $GITHUB_PATH

    - name: Run Staticcheck
      run: staticcheck ./...


    - name: Build
      run: |
        go mod download
        go install gotest.tools/gotestsum@latest

    - name: Test
      run: |
        gotestsum --format=standard-verbose --junitfile=junit.xml

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/junit.xml'
        detailed_summary: true
        include_passed: true
